[package]
name = "tugboat-controller-manager"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
async-trait.workspace = true
base64.workspace = true
clap = { workspace = true, features = ["derive"] }
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
sha2.workspace = true
tokio = { workspace = true, features = ["full"] }
toml.workspace = true
rand.workspace = true
tonic.workspace = true

thiserror.workspace = true
tracing.workspace = true
tracing-subscriber = { workspace = true, features = ["env-filter"] }

tugboat-client.workspace = true
tugboat-csi-operator.workspace = true
tugboat-resources.workspace = true
