// Copyright 2025- SiLeader (Cerussite).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

syntax = "proto3";

import "authorization/v1/policy_rule.proto";
import "meta/v1/object_meta.proto";
import "meta/v1/type_meta.proto";

package tugboat.authorization.v1;

message Role {
  tugboat.meta.v1.TypeMeta type_meta = 1;
  tugboat.meta.v1.ObjectMeta object_meta = 2;
  repeated PolicyRule rules = 3;
}
