# Copyright 2025- SiLeader (Cerussite).
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

[workspace]
members = [
    "tugboat-resources",
    "tugboat-apiserver",
    "tugboat-agent",
    "tugboat-runtime",
    "tugboat-resource-store",
    "tugboat-client",
    "tugboat-cli",
    "tugboat-vm-image",
    "tugboat-vm-runtime-interface",
    "tugboat-cni-operator",
    "tugboat-csi-operator",
    "tugboat-scheduler",
]
resolver = "3"

[workspace.package]
edition = "2024"
license = "Apache-2.0"

[workspace.dependencies]
tugboat-resource-store = { path = "tugboat-resource-store" }
tugboat-resources = { path = "tugboat-resources" }
tugboat-runtime = { path = "tugboat-runtime" }
tugboat-client = { path = "tugboat-client" }
tugboat-vm-image = { path = "tugboat-vm-image" }
tugboat-vm-runtime-interface = { path = "tugboat-vm-runtime-interface" }
tugboat-cni-operator = { path = "tugboat-cni-operator" }
tugboat-csi-operator = { path = "tugboat-csi-operator" }

# command line
clap = "4.5.53"

# serde
serde = "1.0.228"
toml = "1.0.2"
serde_json = "1.0.149"
json_value_merge = "2.0.1"

# protobuf
tonic = "0.14.5"
prost = "0.14.1"
tonic-prost-build = "0.14.5"
prost-build = "0.14.1"

# async
tokio = "1.49.0"
async-trait = "0.1.89"
futures = "0.3.32"
async-stream = "0.3.6"
tokio-util = "0.7.18"

# tls
openssl = "0.10.75"

# rand
rand = "0.10.0"
rand_xorshift = "0.5.0"

# log
tracing = "0.1.44"
tracing-subscriber = "0.3.22"

# HTTP server
actix-web = "4.12.1"
actix-web-lab = "0.24.3"
utoipa = "5.4.0"
utoipa-actix-web = "0.1.2"

# HTTP client
url = "2.5.8"

# store
etcd-client = "0.18.0"

# OCI
oci-distribution = "0.11.0"
sha2 = "0.10.9"
flate2 = "1.1.8"

# QEMU
qapi = "0.15.0"

# misc
regex = "1.12.3"
thiserror = "2.0.17"
uuid = "1.19.0"
base64 = "0.22.1"
nix = "0.30.1"
