[workspace]
members = ["resources", "tugboat-runtime"]

[workspace.package]
edition = "2024"

[workspace.dependencies]
resources = { path = "./resources" }
tugboat-runtime = { path = "./tugboat-runtime" }

# command line
clap = "4.5.53"

# serde
serde = "1.0.228"

# async
tokio = "1.48.0"
async-trait = "0.1.89"

#
regex = "1.12.2"

thiserror = "2.0.17"

[package]
name = "tugboat"
version = "0.1.0"
edition.workspace = true

[dependencies]
tugboat-runtime.workspace = true

clap = { workspace = true, features = ["derive"] }
tokio = { workspace = true, features = ["full"] }
