[package]
name = "tugboat-cli"
version = "0.1.0"
edition.workspace = true

[dependencies]
tugboat-vm-image = { workspace = true, features = ["push"] }

tokio = { workspace = true, features = ["full"] }

clap = { workspace = true, features = ["derive"] }

regex.workspace = true

tracing.workspace = true
tracing-subscriber = { workspace = true, features = ["env-filter"] }

thiserror.workspace = true
