---
- name: Install Tugboat control plane
  hosts: tugboat_control_plane
  become: true
  roles:
    - common
    - role: tugboat_bootstrap
      vars:
        tugboat_bootstrap_stage: pki
    - tugboat_control_plane
    - role: tugboat_bootstrap
      vars:
        tugboat_bootstrap_stage: post

- name: Install Tugboat workers
  hosts: tugboat_workers
  become: true
  roles:
    - common
    - tugboat_worker

- name: Install Tugboat CSI hostpath
  hosts: tugboat_csi_hostpath
  become: true
  roles:
    - role: csi_hostpath
      when: tugboat_csi_hostpath_enabled | bool
