# Copyright 2025- SiLeader (Cerussite).
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1
kind: Fleet
metadata:
  namespace: default
  name: my-fleet
spec:
  network:
    ipv4: 172.16.0.0/16
  ships:
    - name: control-plane
      replicas: 1
      selector:
        matchLabels:
          app: control-plane
      shipTemplate:
        metadata:
          labels:
            app: control-plane
        spec:
          image: ghcr.io/sileader/tugboat-vm-images/ubuntu:24.04
          shipClass: kubernetes-control-plane
    - name: worker-compute-optimized
      network:
        private: true
      replicas: 1
      selector:
        matchLabels:
          app: worker-compute-optimized
      shipTemplate:
        metadata:
          labels:
            app: worker-compute-optimized
        spec:
          image: ghcr.io/sileader/tugboat-vm-images/ubuntu:24.04
          shipClass: compute-optimized
    - name: worker-memory-optimized
      network:
        private: true
      replicas: 1
      selector:
        matchLabels:
          app: worker-memory-optimized
      shipTemplate:
        metadata:
          labels:
            app: worker-memory-optimized
        spec:
          image: ghcr.io/sileader/tugboat-vm-images/ubuntu:24.04
          shipClass: memory-optimized
