// Copyright 2025- SiLeader (Cerussite).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

syntax = "proto3";

import "meta/v1/type_meta.proto";
import "meta/v1/object_meta.proto";
import "meta/v1/time.proto";

package tugboat.core.v1;

message Node {
  meta.v1.TypeMeta type_meta = 1;
  meta.v1.ObjectMeta object_meta = 2;
  NodeSpec spec = 3;
  optional NodeStatus status = 4;
}

message NodeSpec {
  NodeOvercommitSpec overcommit = 1;
  repeated string ips = 2;
  NodeResource resource = 3;
  repeated Taint taints = 4;
}

message Taint {
  string key = 1;
  string value = 2;
  string effect = 3;
}

message NodeOvercommitSpec {
  string cpu_ratio = 1;
  string memory_ratio = 2;
}

message NodeResource {
  uint64 cpu = 1;
  uint64 memory = 2;
}

message NodeStatus {
  repeated NodeCondition conditions = 1;
  repeated NodeCniPluginStatus cni_plugins = 2;
}

message NodeCondition {
  string type = 1;
  string status = 2;
  string message = 3;
  meta.v1.Time timestamp = 4;
}

message NodeCniPluginStatus {
  string name = 1;
  optional bool ready = 2;
  string message = 3;
}
