// Copyright 2025- SiLeader (Cerussite).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

syntax = "proto3";

import "meta/v1/type_meta.proto";
import "meta/v1/object_meta.proto";

import "core/v1/secret.proto";

package tugboat.core.v1;

message PersistentVolume {
  meta.v1.TypeMeta type_meta = 1;
  meta.v1.ObjectMeta object_meta = 2;
  PersistentVolumeSpec spec = 3;
  PersistentVolumeStatus status = 4;
}

message PersistentVolumeSpec {
  repeated string access_modes = 1;
  string persistent_volume_reclaim_policy = 2;
  string storage_class_name = 3;
  string volume_mode = 4;
  CsiPersistentVolumeSource csi = 5;
}

message PersistentVolumeStatus {
}

message CsiPersistentVolumeSource {
  string driver = 1;
  SecretReference controller_expand_secret_ref = 2;
  SecretReference controller_publish_secret_ref = 3;
  SecretReference node_expand_secret_ref = 4;
  SecretReference node_publish_secret_ref = 5;
  SecretReference node_stage_secret_ref = 6;
  bool read_only = 7;
  string volume_handle = 8;
}