syntax = "proto3";

import "meta/v1/object_meta.proto";
import "meta/v1/time.proto";
import "meta/v1/type_meta.proto";

package tugboat.core.v1;

message Ship {
  meta.v1.TypeMeta type_meta = 1;
  meta.v1.ObjectMeta object_meta = 2;
  ShipSpec spec = 3;
}

message ShipSpec {
  string image = 1;
  string ship_class = 2;
  optional string node_name = 3;
}

message ShipStatus {
  repeated ShipCondition conditions = 1;
  repeated ShipIp ips = 2;
}

message ShipCondition {
  string status = 1;
  string message = 2;
  meta.v1.Time timestamp = 3;
}

message ShipIp {
  string nic = 1;
  optional string ipv4 = 2;
  optional string ipv6 = 3;
}
