// Copyright 2025- SiLeader (Cerussite).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

syntax = "proto3";

import "meta/v1/object_meta.proto";
import "meta/v1/time.proto";
import "meta/v1/type_meta.proto";

import "core/v1/network_class.proto";
import "core/v1/selector.proto";

package tugboat.core.v1;

message Ship {
  meta.v1.TypeMeta type_meta = 1;
  meta.v1.ObjectMeta object_meta = 2;
  ShipSpec spec = 3;
  optional ShipStatus status = 4;
}

message ShipSpec {
  string image = 1;
  string ship_class = 2;
  optional string node_name = 3;
  repeated ShipNetworkClassReference network_class_ref = 4;
  optional ShipUefi uefi = 5;
  repeated Toleration tolerations = 6;
  optional string scheduler_name = 7;
  repeated ShipVolumeClaimReference volume_claim_ref = 8;
  repeated ShipVolume volumes = 9;
  optional string target_node_name = 10;
  optional string runtime_class = 11;
  optional string service_account_name = 12;
  optional bool automount_service_account_token = 13;
  optional Affinity affinity = 14;
  repeated TopologySpreadConstraint topology_spread_constraints = 15;
}

message Affinity {
  optional NodeAffinity node_affinity = 1;
  optional ShipAffinity ship_affinity = 2;
  optional ShipAntiAffinity ship_anti_affinity = 3;
}

message NodeAffinity {
  optional NodeSelector required_during_scheduling = 1;
  repeated PreferredSchedulingTerm preferred_during_scheduling = 2;
}

message PreferredSchedulingTerm {
  int32 weight = 1;
  NodeSelectorTerm preference = 2;
}

message ShipAffinity {
  repeated ShipAffinityTerm required_during_scheduling = 1;
  repeated WeightedShipAffinityTerm preferred_during_scheduling = 2;
}

message ShipAntiAffinity {
  repeated ShipAffinityTerm required_during_scheduling = 1;
  repeated WeightedShipAffinityTerm preferred_during_scheduling = 2;
}

message ShipAffinityTerm {
  optional meta.v1.LabelSelector label_selector = 1;
  repeated string namespaces = 2;
  string topology_key = 3;
}

message WeightedShipAffinityTerm {
  int32 weight = 1;
  ShipAffinityTerm ship_affinity_term = 2;
}

message TopologySpreadConstraint {
  int32 max_skew = 1;
  string topology_key = 2;
  string when_unsatisfiable = 3;
  optional meta.v1.LabelSelector label_selector = 4;
}

message ShipVolumeClaimReference {
  string name = 1;
}

message ShipVolume {
  string name = 1;
  optional PersistentVolumeClaimVolumeSource persistent_volume_claim = 2;
  optional ConfigMapVolumeSource config_map = 3;
  optional SecretVolumeSource secret = 4;
  optional ProjectedVolumeSource projected = 5;
}

message PersistentVolumeClaimVolumeSource {
  string claim_name = 1;
}

message KeyToPath {
  string key = 1;
  string path = 2;
}

message ConfigMapVolumeSource {
  string name = 1;
  repeated KeyToPath items = 2;
  optional int32 default_mode = 3;
  optional bool optional = 4;
}

message SecretVolumeSource {
  string secret_name = 1;
  repeated KeyToPath items = 2;
  optional int32 default_mode = 3;
  optional bool optional = 4;
}

message ProjectedVolumeSource {
  repeated VolumeProjection sources = 1;
  optional int32 default_mode = 2;
}

message VolumeProjection {
  optional ServiceAccountTokenProjection service_account_token = 1;
  optional ConfigMapProjection config_map = 2;
  optional SecretProjection secret = 3;
}

message ServiceAccountTokenProjection {
  optional string audience = 1;
  optional int64 expiration_seconds = 2;
  string path = 3;
}

message ConfigMapProjection {
  string name = 1;
  repeated KeyToPath items = 2;
  optional bool optional = 3;
}

message SecretProjection {
  string name = 1;
  repeated KeyToPath items = 2;
  optional bool optional = 3;
}

message Toleration {
  optional string key = 1;
  string operator = 2;
  optional string value = 3;
  string effect = 4;
  optional int64 toleration_seconds = 5;
}

message ShipStatus {
  repeated ShipCondition conditions = 1;
  repeated ShipIp ips = 2;
  optional ShipMigrationStatus migration = 3;
  optional ShipActualAllocation actual_allocation = 4;
}

message ShipActualAllocation {
  optional uint64 cpu_cores = 1;
  optional string memory_size = 2;
  repeated string nic_ids = 3;
  repeated string volume_ids = 4;
}

message ShipMigrationStatus {
  string phase = 1;
  optional string source_node_name = 2;
  optional string target_node_name = 3;
  optional string target_address = 4;
  optional uint32 target_port = 5;
  string message = 6;
  optional meta.v1.Time timestamp = 7;
  optional uint64 bytes_transferred = 8;
  optional uint64 bytes_remaining = 9;
}

message ShipCondition {
  string status = 1;
  string message = 2;
  meta.v1.Time timestamp = 3;
}

message ShipIp {
  string nic = 1;
  optional string ipv4 = 2;
  optional string ipv6 = 3;
}

message ShipUefi {
  bool enabled = 1;
}
