// Copyright 2025- SiLeader (Cerussite).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

syntax = "proto3";

import "meta/v1/object_meta.proto";
import "meta/v1/type_meta.proto";
import "core/v1/secret.proto";

package tugboat.core.v1;

message StorageClass {
  meta.v1.TypeMeta type_meta = 1;
  meta.v1.ObjectMeta object_meta = 2;
  StorageClassSpec spec = 3;
}

message StorageClassSpec {
  string provisioner = 1;
  map<string, string> parameters = 2;
  optional string reclaim_policy = 3;
  optional string fs_type = 4;
  optional bool allow_volume_expansion = 5;
  SecretReference controller_expand_secret_ref = 6;
  SecretReference controller_publish_secret_ref = 7;
  SecretReference node_expand_secret_ref = 8;
  SecretReference node_publish_secret_ref = 9;
  SecretReference node_stage_secret_ref = 10;
  SecretReference controller_create_secret_ref = 11;
  repeated string mount_options = 12;
}
