apiVersion: v1
kind: Ship
metadata:
  name: topology-aware-ship
  namespace: demo
spec:
  image: ghcr.io/sileader/tugboat-vm-images/ubuntu:24.04
  shipClass: small
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: topology.tugboat.cloud/zone
                operator: In
                values:
                  - zone-a
