# Copyright 2025- SiLeader (Cerussite).
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

[package]
name = "tugboat-apiserver"
version = "0.1.0"
edition.workspace = true

[dependencies]
tugboat-resource-store.workspace = true
tugboat-resources = { workspace = true, features = ["schema", "validators"] }

actix-web = { workspace = true, features = ["rustls-0_23"] }
actix-web-lab.workspace = true
utoipa = { workspace = true, features = ["actix_extras"] }
utoipa-actix-web.workspace = true

rustls.workspace = true
rustls-pemfile.workspace = true

serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true

rand.workspace = true
rand_xorshift.workspace = true

tokio = { workspace = true, features = ["full"] }
async-stream.workspace = true

uuid = { workspace = true, features = ["v4"] }

thiserror.workspace = true

clap = { workspace = true, features = ["derive"] }

tracing.workspace = true
tracing-subscriber = { workspace = true, features = ["env-filter"] }

toml.workspace = true
