[package]
name = "tugboat-apiserver"
version = "0.1.0"
edition.workspace = true

[dependencies]
tugboat-resource-store.workspace = true
tugboat-resources.workspace = true

actix-web.workspace = true
utoipa = { workspace = true, features = ["actix_extras"] }
utoipa-actix-web.workspace = true

serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
