# Copyright 2025- SiLeader (Cerussite).
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

[package]
name = "tugboat-agent"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
tugboat-client.workspace = true
tugboat-resources.workspace = true
tugboat-vm-image = { workspace = true, features = ["pull"] }
tugboat-vm-runtime-interface.workspace = true

serde = { workspace = true, features = ["derive"] }
toml.workspace = true
serde_json.workspace = true

clap = { workspace = true, features = ["derive"] }

tracing.workspace = true
tracing-subscriber = { workspace = true, features = ["env-filter"] }

futures.workspace = true
tokio = { workspace = true, features = ["full"] }

thiserror.workspace = true

oci-distribution.workspace = true
