[package]
name = "tugboat-agent"
version = "0.1.0"
edition.workspace = true

[dependencies]
tugboat-client.workspace = true
tugboat-resources.workspace = true
tugboat-vm-image = { workspace = true, features = ["pull"] }

serde = { workspace = true, features = ["derive"] }
toml.workspace = true
serde_json.workspace = true

clap = { workspace = true, features = ["derive"] }

tracing.workspace = true
tracing-subscriber = { workspace = true, features = ["env-filter"] }

futures.workspace = true
tokio = { workspace = true, features = ["full"] }

thiserror.workspace = true

oci-distribution.workspace = true
