[http]
listen = "${APISERVER_LISTEN}"
${APISERVER_TLS_CONFIG}

[etcd]
endpoints = [${APISERVER_ETCD_ENDPOINTS}]
${APISERVER_ETCD_TLS_CONFIG}

[authorization]
mode = "${APISERVER_AUTHORIZATION_MODE}"

[authentication]
anonymous_enabled = ${APISERVER_ANONYMOUS_ENABLED}
${APISERVER_SERVICE_ACCOUNT_TOKEN_CONFIG}

${APISERVER_AUDIT_CONFIG}
