[package]
name = "tugboat-resources"
version = "0.1.0"
edition.workspace = true

[dependencies]
serde = { workspace = true, features = ["derive"] }

prost.workspace = true

regex = { workspace = true, optional = true }

utoipa = { workspace = true, optional = true }

[build-dependencies]
prost-build.workspace = true

[features]
schema = ["utoipa"]
validators = ["regex"]
