# Note: This is a representation of the TokenRequest API object.
# It is typically used via 'POST /v1/namespaces/{ns}/serviceaccounts/{name}/token'
# rather than 'apply -f'.
apiVersion: authorization/v1
kind: TokenRequest
spec:
  audiences:
    - https://apiserver.tugboat.cloud
  expirationSeconds: 3600
# response:
#   token: "eyJhbGciOiJSUzI1NiIs..."
#   expirationTimestamp: "2026-05-11T11:00:00Z"
